version: '3.7'

services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  storage_api:
    image: renews-storage
    restart: always
    ports:
      - 5000:5000
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_HOST: ${PG_HOST}
      PG_PORT: ${PG_PORT}
    depends_on:
      - "db"
    volumes:
      - ./storage/articles:/var/articles